name: Create and Save Tar Archive

on:
  push:
    branches:
      - main

jobs:
  create_and_save_tar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Identify Changed Files
      id: changed_files
      run: |
        git diff-tree --no-commit-id --name-only -r HEAD > changed_files.txt
        cat changed_files.txt

    - name: Create Tar Archive
      run: |
        tar -czvf changed_files.tar.gz -T changed_files.txt
        ls -l changed_files.tar.gz

    - name: Copy Tar Archive to Repository
      run: |
        # Copy the tar file to a directory within the repository
        cp changed_files.tar.gz $GITHUB_WORKSPACE/changed_files.tar.gz

    - name: Print Archive Path
      run: |
        echo "Path to Tar Archive: $GITHUB_WORKSPACE/changed_files.tar.gz"

    - name: Display Archive Contents
      run: |
        tar -tzvf $GITHUB_WORKSPACE/changed_files.tar.gz

    - name: Commit and Push Tar Archive
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add changed_files.tar.gz
        git commit -m "Add changed_files.tar.gz"
        git push
