name: Create and Save Tar Archive

on:
  push:
    branches:
      - main

jobs:
  create_and_save_tar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Identify Changed Files
      id: changed_files
      run: |
        git diff-tree --no-commit-id --name-only -r HEAD > changed_files.txt
        cat changed_files.txt

    - name: Create Tar Archive
      run: |
        tar -czvf changed_files.tar.gz -T changed_files.txt
        ls -l changed_files.tar.gz

    - name: Copy Tar Archive to Repository
      run: |
        cp changed_files.tar.gz $GITHUB_WORKSPACE/changed_files_new.tar.gz

    - name: Print Archive Path
      run: |
        echo "Path to Tar Archive: $GITHUB_WORKSPACE/changed_files_new.tar.gz"

    - name: Display Archive Contents
      run: |
        tar -tzvf $GITHUB_WORKSPACE/changed_files_new.tar.gz

    - name: Configure Git
      run: |
        git config --global user.email "${GITHUB_EMAIL}"
        git config --global user.name "${GITHUB_ACTOR}"

    - name: Push to Main Branch
      run: |
        # Set up the GitHub repository URL
        git remote set-url origin "https://github.com/${{ github.repository }}.git"

        # Authenticate using a Personal Access Token (PAT) with write access
        git fetch --no-tags --prune --progress --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git checkout main
        git add changed_files_new.tar.gz
        git commit -m "Add changed_files_new.tar.gz"
        git push origin main
