name: Create and Save Tar Archive

on:
  push:
    branches:
      - main

jobs:
  create_and_save_tar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Identify Changed Files
      id: changed_files
      run: |
        git diff-tree --no-commit-id --name-only -r HEAD > changed_files.txt
        cat changed_files.txt

    - name: Create Tar Archive
      run: |
        tar -czvf changed_files.tar.gz -T changed_files.txt
        ls -l changed_files.tar.gz

    - name: Save Archive Locally
      run: |
        mv changed_files.tar.gz $HOME/changed_files.tar.gz

    - name: Print Archive Path
      run: |
        echo "Path to Tar Archive: $HOME/changed_files.tar.gz"

    - name: Display Archive Contents
      run: |
        tar -tzvf $HOME/changed_files.tar.gz

    - name: Upload Tar Archive
      uses: actions/upload-artifact@v2
      with:
        name: changed-files
        path: $HOME/changed_files.tar.gz

    # Ensure the artifact is uploaded even if previous steps fail
    - name: Upload Always
      if: always()
      run: echo "Workflow completed, even if previous steps failed."
